Ecomerce/Ecomerce/Models/Customer.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ecomerce.Models
{
    public class Customer
    {
        [Key]
        public int CustomerId { get; set; }

        [Required(ErrorMessage = "First name is required.")]
        [StringLength(50, ErrorMessage = "First name must be between 1 and 50 characters.", MinimumLength = 1)]
        public string? FirstName { get; set; }

        [Required(ErrorMessage = "Last name is required.")]
        [StringLength(50, ErrorMessage = "Last name must be between 1 and 50 characters.", MinimumLength = 1)]
        public string? LastName { get; set; }

        [Required(ErrorMessage = "Country is required.")]
        public string? Country { get; set; }

        [Required(ErrorMessage = "Address is required.")]
        public string? Address { get; set; }

        [Required(ErrorMessage = "City is required.")]
        public string? City { get; set; }

        [Required(ErrorMessage = "Governorate is required.")]
        public string? Governorate { get; set; }

        [Required(ErrorMessage = "Postal code is required.")]
        [StringLength(10, ErrorMessage = "Postal code must be between 1 and 10 characters.", MinimumLength = 1)]
        public string? PostalCode { get; set; }

        public string? AdditionalAddressInfo { get; set; }

        [Required(ErrorMessage = "Phone number is required.")]
        [Phone(ErrorMessage = "Invalid phone number.")]
        public string? PhoneNumber { get; set; }

        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress(ErrorMessage = "Invalid email address.")]
        public string? Email { get; set; }

        [Display(Name = "Text me with news and offers")]
        public bool IsNewsOn { get; set; }

      
        public Order Order { get; set; }
    }
}

Ecomerce/Ecomerce/Models/Order.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace Ecomerce.Models
{
    public class Order
    {
        [Key]
        public int OrderId { get; set; }
        [MaxLength(50)]
        public string OrderNumber { get; set; }
        [Required]
        public DateTime OrderDate { get; set; }
        public DateTime ShipDate { get; set; }
        public bool Deleted { get; set; }
        public bool Paid { get; set; }
        [Required]
        [MaxLength(50)]
        public int CustomerId { get; set; }
        [ForeignKey("CustomerId")]
        public Customer Customer { get; set; }
        public ICollection<OrderDetails> OrderDetails { get; set; }

    }
}

Ecomerce/Ecomerce/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace Ecomerce.Models
{
	public class Product
	{
        [Key]
        public int? Product_Id { get; set; }
		[Required(ErrorMessage ="name is required")]
		[Display(Name="Product name")]
        public string? Product_name { set; get; }
		
		public string? Product_description { set; get; }

        public int? Product_rate { set; get; }

        public List<ProductCategoriy> Product_Categoriys { get; set; } = new List<ProductCategoriy>();
        public List<ProductSize> Product_sizes { get; set; } = new List<ProductSize>();
		public List<Style>? Product_styles { set; get; }
		public List<Block>? Product_blocks { set; get; }	

		
	}
}

Ecomerce/Ecomerce/Controllers/AdminController.cs
using Ecomerce.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Ecomerce.Data;
using Ecomerce.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
//these 2 libarariys are for working with an file 
using System.IO;
using Microsoft.AspNetCore.Hosting;
using static System.Reflection.Metadata.BlobBuilder;
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json;
using Ecomerce.SeessionModels;
using System.IdentityModel.Tokens.Jwt;
using Microsoft.AspNetCore.Authorization;
using System.Linq;

namespace Ecomerce.Controllers
{

   [Authorize(Roles ="Admin,Owner")]
   public class AdminController : Controller
   {

      
       private readonly IWebHostEnvironment _webHost;
       private readonly SystemContext systemContext;

        public AdminController(IWebHostEnvironment webHost,SystemContext _systemContext)
        {

           _webHost = webHost;
            systemContext = _systemContext;
        }
        //first fase in create
       [HttpGet]
       public IActionResult AddProductGenerall()
       {
           
           FirstPartOfFormOfProductViewModel firstPart = new FirstPartOfFormOfProductViewModel() { };

           firstPart.Categories = systemContext.Categorias.Select(x => new SelectListItem() { Value = x.Categoriy_Id.ToString(), Text = x.Categoriy_Name }).ToList();
           firstPart.Sizes = systemContext.Sizes.Select(x => new SelectListItem() { Value = x.SizeID.ToString(), Text = x.size.ToString() }).ToList();

           return View(firstPart);
       }

       [HttpPost]
       public IActionResult AddProductGenerall(FirstPartOfFormOfProductViewModel firstPart)
       {
           if (true)
           {
             string serialized = JsonConvert.SerializeObject(firstPart);
             HttpContext.Session.SetString("generalInfo", serialized);

             return RedirectToAction("SetBlocks");
           }

           return View(firstPart);
       }


        // second faze in create

       [HttpGet]
       public IActionResult SetBlocks()
       {


          List<BlockWithFile> blocks = new List<BlockWithFile>();
          
          blocks.Insert(0, new BlockWithFile { block=new Block()});

          return View(blocks);
       }
       [HttpPost]
       public IActionResult SetBlocks(List<BlockWithFile> blocks)
       {
          


           foreach (var block in blocks)
           {

                if (block.File != null && block.File.Length > 0)
                {
                
                
                    string uniqueFileName = GetUploadedFileName(block.File);
                    if (uniqueFileName != null && uniqueFileName != "")
                    {
                        block.block.Block_image = uniqueFileName;
                    }
                
                }


           }

           if (blocks[0].block.Block_description == null)
           {

              
               return View(blocks);
           }
           else
           {
               string serialized = JsonConvert.SerializeObject(blocks.Select(x => x.block));
               HttpContext.Session.SetString("blocks", serialized);
               return RedirectToAction("SetStyles");
           }


       }

        //third faze in create
       [HttpGet]
       public IActionResult SetStyles()
       {
   
           List<StyleWithFiles> styles = new List<StyleWithFiles>();
           styles.Insert(0, new StyleWithFiles {style=new Style { },files=new List<FileOfImage>() });
           styles[0].style.Style_images = new List<Image>();
           styles[0].style.Style_images.Insert(0, new Image { });
           IFormFile? file = null;
           styles[0].files.Insert(0,new FileOfImage());

       return View(styles);
       }
       [HttpPost]
       public IActionResult SetStyles(List<StyleWithFiles> styles)
       {

       
          
           foreach (var style in styles)
           {

                for(int i= 0; i< style?.files?.Count() ; i++)
                {

                    if (style?.files?[i] != null && style?.files[i].file?.Length >0)
                    {


                        string uniqueFileName = GetUploadedFileName(style.files[i].file);
                        if (uniqueFileName != null && uniqueFileName != "")
                        {
                           style.style.Style_images[i].Image_url = uniqueFileName;
                        }

                    }
                }
               

           }

           if (true)
           {
           // Store the serialized styles in session
               string serialized = JsonConvert.SerializeObject(styles.Select(x=>x.style));
               HttpContext.Session.SetString("styles", serialized);
            
               return RedirectToAction("SetQuntatiy");
           }
           return View(styles);
       }

        // fourth fase in create
       [HttpGet]
       public IActionResult SetQuntatiy()
       {
            FirstPartOfFormOfProductViewModel general= JsonConvert.DeserializeObject<FirstPartOfFormOfProductViewModel>(HttpContext.Session.GetString("generalInfo"));


            List<Size> sizes = new List<Size>();
            foreach (var siz in general?.Product_sizes)
            {
                sizes.Add(systemContext.Sizes.Single(x => x.SizeID == siz));
            }

            List<Style> styles=JsonConvert.DeserializeObject<List<Style>>(HttpContext.Session.GetString("styles"));



            List<StyleSize> quantatis = new List<StyleSize>();
           for (int i = 0; i < styles?.Count(); i++)
           {
               for (int j = 0; j < sizes?.Count(); j++)
               {
                    StyleSize item = new StyleSize();
                    item.Style = styles[i];
                    item.size= sizes[j];
                    item.SizeId = sizes[j].SizeID;
                  
                    item.quantity = 0;
                    quantatis.Add(item);
               }
           }

          
           return View(quantatis);
       }
        [HttpPost]
        public IActionResult SetQuntatiy(List<StyleSize> quantatis)
        {

            string serialized = JsonConvert.SerializeObject(quantatis);
            HttpContext.Session.SetString("quantatis", serialized);
           Console.WriteLine(serialized);
            return RedirectToAction("create");
            
        }

        //the last fase in create => Add to data base
        [HttpGet]
        public IActionResult create()
        {
            Product product = new Product();
            FirstPartOfFormOfProductViewModel generalInfo = JsonConvert.DeserializeObject<FirstPartOfFormOfProductViewModel>(HttpContext.Session.GetString("generalInfo"));

            List<Block>blocks= JsonConvert.DeserializeObject<List<Block>>(HttpContext.Session.GetString("blocks"));

            List<Style>styles= JsonConvert.DeserializeObject<List<Style>>(HttpContext.Session.GetString("styles"));
          
            if (generalInfo == null || blocks == null || styles == null)
            {
                return RedirectToAction("Error");
            }

            product.Product_name = generalInfo?.Product_name;
            product.Product_description = generalInfo?.Product_description;
            product.Product_rate= generalInfo?.Product_rate;

            

            product.Product_Categoriys = generalInfo?.Product_Categoriys.Select(x => new ProductCategoriy() { CategoriyId = x }).ToList();
           
            
            product.Product_sizes= generalInfo?.Product_sizes.Select(x => new ProductSize() { SizeId = x }).ToList();

           
            product.Product_blocks=blocks;
            product.Product_styles=styles;


            string serialized = JsonConvert.SerializeObject(product);
            HttpContext.Session.SetString("product", serialized);

           
            product.Product_sizes = generalInfo?.Product_sizes.Select(x => new ProductSize() { SizeId = x ,size=systemContext.Sizes.Where(s=>s.SizeID==x).FirstOrDefault()}).ToList();

            
            return View(product);
        }

        [HttpPost]
        public IActionResult create(Product product)
        {
            product = JsonConvert.DeserializeObject<Product>(HttpContext.Session.GetString("product"));
           
            systemContext.ProductList.Add(product);
            systemContext.SaveChanges();


            //List<Style> styles = new List<Style>();
            //styles = systemContext.ProductList.OrderBy(p=>p.Product_Id).Last().Product_styles;
            //List<StyleSize> quantatis = JsonConvert.DeserializeObject<List<StyleSize>>(HttpContext.Session.GetString("quantatis"));
            //foreach (var styleSize in quantatis)
            //{
            //    // Find the Style associated with the StyleSize
            //    var style = styles.FirstOrDefault(s => s.Style_name == styleSize.Style.Style_name);
            //    if (style != null)
            //    {
            //        // Assign the found Style to the StyleSize
            //        styleSize.Style = style;
                    

            //    }
            //    styleSize.StyleId = null;
            //    styleSize.SizeId = null;
            //}
            //Console.WriteLine("..............................");

            //string serialized = JsonConvert.SerializeObject(quantatis);
            
            //Console.WriteLine(serialized);
            //systemContext.StyleSizes.AddRange(quantatis);
            //systemContext.SaveChanges();
            return RedirectToAction("Products");
        }


        //Create an file for the image and creat an uniqe name for it
        private string GetUploadedFileName(IFormFile? imgfile)
        {
           string uniqueFileName = null;

           if (imgfile != null)
           {
               string uploadsFolder = Path.Combine(_webHost.WebRootPath, "images");
               uniqueFileName = Guid.NewGuid().ToString() + "_" + imgfile.FileName;

Ecomerce/Ecomerce/Controllers/ProductController.cs
using Ecomerce.Data;
using Ecomerce.Models;
using Ecomerce.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace Ecomerce.Controllers
{
    public class ProductController : Controller
    {
        private readonly SystemContext systemContext;

        public ProductController(SystemContext _systemContext)
        {
            systemContext = _systemContext;
        }
        public IActionResult getProductByIdAndStyleId(int id,int sid)
        {

            var product = systemContext.ProductList.Where(x => x.Product_Id == id);
            product = product.Include(x => x.Product_styles).ThenInclude(s => s.Style_images);
            product = product.Include(x => x.Product_blocks);
            product = product.Include(x => x.Product_sizes).ThenInclude(s => s.size);
            List<Product> p = product.ToList();
            ProductStyleIndexViewModel viewModel = new ProductStyleIndexViewModel();
            viewModel.product = p[0];viewModel.sid = sid;   
            return View(viewModel);
        }
    }
}

Ecomerce/Ecomerce/Controllers/RoleController.cs
using Ecomerce.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Ecomerce.Controllers
{
  
   
    [Authorize(Roles = "Owner")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;

        public RoleController(RoleManager<IdentityRole> _roleManager)
        {
            roleManager = _roleManager;
        }
        [HttpGet]
        public IActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(RoleViewModel newRole)
        {
            if(ModelState.IsValid)
            {

                IdentityRole role = new IdentityRole();
                role.Name = newRole.RoleName;

               IdentityResult result= await roleManager.CreateAsync(role);
                if(result.Succeeded)
                {
                    return View();
                }
                else {

                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
          
            return View(newRole);
        }


        [HttpGet]
        public IActionResult AddAdmin()
        {
            return View();
        }
      


    }
}

Ecomerce/Ecomerce/Views/Admin/AddProductGenerall.cshtml
@using Ecomerce.ViewModels;
@model FirstPartOfFormOfProductViewModel;
@{
    ViewData["Title"] = "AddProductGenerall";
    Layout = "_my_layout";
}
<link href="~/css/generaldetails.css" rel="stylesheet" />
<h1 style="margin-left:25px">AddProductGenerall</h1>

<link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />
<form asp-controller="Admin" asp-action="AddProductGenerall" method="post" style="display:grid;gap:40px;grid-column:1">

    <div id="generalProductInformations" class="container" style="display:flex;justify-content:center;align-items:center;flex-direction:column;">
       
            <div class="box">
                <label asp-for="Product_name" class="form-label"></label>
                <input type="text" asp-for="Product_name" class="form-control" placeholder="Enter product name" />
                <span asp-validation-for="Product_name" class="text-danger"></span>
            </div>


            <div class="box">

                <label asp-for="Product_description" class="form-label"></label>
                <input type="text" asp-for="Product_description" class="form-control" placeholder="Enter product description" />
                <span asp-validation-for="Product_description" class="text-danger"></span>
            </div>

            <div class="box">

                <label asp-for="Product_rate" class="form-label"></label>
                <input type="text" asp-for="Product_rate" class="form-control" placeholder="Enter product rate" />
                <span asp-validation-for="Product_rate" class="text-danger"></span>
            </div>


            <div class="box">

                <label asp-for="Product_Categoriys" class="form-label"></label>
                <select asp-for="Product_Categoriys" asp-items="Model.Categories" class="form-control" placeholder="Enter product description">
                    <option>Select categorits</option>
                </select>
                <span asp-validation-for="Product_Categoriys" class="text-danger"></span>
            </div>


            <div class="box">

                <label asp-for="Product_sizes" class="form-label"></label>
                <select asp-for="Product_sizes" asp-items="Model.Sizes" class="form-control" placeholder="Enter product description">
                    <option>select Sizes</option>
                </select>
                <span asp-validation-for="Product_sizes" class="text-danger"></span>
            </div>
        

       

    </div>

    <input type="submit" value="next" class="btn btn-primary" />
</form>

Ecomerce/Ecomerce/Views/Admin/AddQuantatity.cshtml
@{
    ViewData["Title"] = "AddQuantatity";
}

<h1 style="text-align:center">AddQuantatity</h1>

Ecomerce/Ecomerce/Views/Admin/Customers.cshtml
@model List<Customer>
@{
    ViewData["Title"] = "Customers";
}
<link href="~/css/ownerpage.css" rel="stylesheet" />

<h1 style="text-align:center">Customers</h1>

<div class="container" style="min-height:600px;">

    

    <partial name="_SideNavBar" />
    <div style="flex-basis:15%"></div>

    <table class="table table-striped table-dark">

        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    FName
                </th>
                <th>
                    LName
                </th>
                <th>
                    Email
                </th>
                <th>
                    Address
                </th>
                <th>
                    Phone
                </th>
                <th>
                   More
                </th>

            </tr>
        </thead>
        <tbody>

            @{
                for (int i = 0; i < Model?.Count(); i++)
                {
                    <tr>
                        <td>
                            @Model[i].CustomerId
                        </td>
                        <td>
                            @Model[i].FirstName
                        </td>
                        <td>
                            @Model[i].LastName
                        </td>
                        <td>
                            @Model[i].Email
                        </td>
                        <td>
                            @Model[i].Address
                        </td>

                        <td>
                            @Model[i].PhoneNumber
                        </td>
                        <td>
                            <a>More</a>
                        </td>
                    </tr>




                }
            }




        </tbody>



    </table>




</div>

Ecomerce/Ecomerce/Views/Admin/HR.cshtml
@using Microsoft.AspNetCore.Identity;

@model List<IdentityUser>
@{
    ViewData["Title"] = "HR";
    
}

<h1 style="text-align:center;margin-bottom:2px;">HR</h1>

<link href="~/css/ownerpage.css" rel="stylesheet" />

<p style="text-align:center;color:gray">Manage your staff!!</p>

<div class="container" style="min-height:600px;">

    <div style="flex-basis:15%"></div>

    <partial name="_SideNavBar" />

    <a asp-action="AddRole" asp-controller="Role" style="position:absolute;top:-3rem;right:0px;">
        <div class="btn btn-outline-info" style="height:fit-content">

            Add Roles
        </div>
    </a>
    <a asp-action="AddAdmin" asp-controller="Role" style="position:absolute;top:-3rem;right:300px;">
        <div class="btn btn-outline-primary" style="height:fit-content">

            Add Admin
        </div>
    </a>
  
    <table class="table table-striped table-dark">

        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                     Name
                </th>
                <th>
                    Email
                </th>
                <th>
                    Worked Date
                </th>
                <th>
                    Role
                </th>

            </tr>
        </thead>
        <tbody>

            @{
                for (int i = 0; i < Model?.Count(); i++)
                {
                     <tr>
                            <td>
                                @Model[i].Id
                            </td>
                            <td>
                                @Model[i].UserName
                            </td>
                            <td>
                                @Model[i].Email
                            </td>
                            <td>
                                now
                            </td>
                            <td>
                                Admin
                            </td>

               
                        </tr>


                    

                }
            }




        </tbody>



    </table>




</div>

Ecomerce/Ecomerce/Views/Admin/Products.cshtml
@model List<Product>
@{
    ViewData["Title"] = "Products";
    Layout = "_my_layout";
}

<h1 style="text-align:center;margin-bottom:2px;">Products</h1>

<link href="~/css/ownerpage.css" rel="stylesheet" />

<p style="text-align:center;color:gray">Here's your product!!</p>

<div class="container" style="min-height:600px;">

    <div style="flex-basis:15%"></div>

    <partial name="_SideNavBar" />
    <a asp-action="AddProductGenerall" asp-controller="Admin" style="position:absolute;top:0px;right:0px;">
        <div class="btn btn-outline-success" style="height:fit-content">

            Add Product
        </div>
    </a>
   
    <div class="container" style="display: grid;
    grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
    grid-column-gap: 40px;
    grid-row-gap: 40px;padding:2rem;margin-top:3rem">

       
            @for (int i = 0; i < Model?.Count(); i++)
            {

            <div class="card" style="width: 18rem;height:10rem;">
                <div class="card-body">
                    <h5 class="card-title">@Model[i].Product_name</h5>
                
                </div>
                <ul class="list-group list-group-flush">
                    
                    
                </ul>
                <div class="card-body">
                    <a class="card-link" style="color:greenyellow" asp-controller="Admin" asp-action="Update" asp-route-Product_Id="@Model[i].Product_Id">update</a>

                    <a class="card-link text-info" asp-controller="Admin" asp-action="AddQuantatity" asp-route-Product_Id="@Model[i].Product_Id">Add to store</a>
                    <a class="card-link text-danger" asp-controller="Admin" asp-action="Delete" asp-route-productId="@Model[i].Product_Id" asp-route-ProductName="@Model[i].Product_name">Delete</a>


                </div>
            </div>
                    

                

            }



       
    </div>

    
    

</div>

Ecomerce/Ecomerce/Views/Admin/SetBlocks.cshtml
@using Ecomerce.SeessionModels;
@{
    @model List<BlockWithFile>
    Layout = "_my_layout";

}

<link href="~/css/setblocks.css" rel="stylesheet" />

<form id="Bform" enctype="multipart/form-data" asp-controller="Admin" asp-action="SetBlocks" method="post" style="display:grid;row-gap:40px;justify-items: center;margin-top:50px">
    @for (int i = 0; i < Model?.Count(); i++)
    {
        <div class="block">

            <div class="block_text" style="flex-basis:50%;">
                <div >
                    <input  asp-for="@Model[i].block.Block_title" class="Block_title" placeholder="TITLE of the block" />
                    <br>
                    <span asp-validation-for="@Model[i].block.Block_title" class="text-danger"></span>
                </div>

                <div style="height:100%">
                    <textarea asp-for="@Model[i].block.Block_description" class="Block_description" placeholder="Description of the block"></textarea>
                    <span asp-validation-for="@Model[i].block.Block_description" class="text-danger"></span>
                </div>

            </div>



            <div class="block_img">
                <div class="form-group">
                    @*  <label asp-for="@Model[i].ImageFile" class="control-label"></label> *@
                    <div class="custom-file">
                        
                        <input  asp-for="@Model[i].File" class="custom-file-input" id="customFile_@i"
                               onchange="document.getElementById('PreviewPhoto_@i').src = window.URL.createObjectURL(this.files[0])" />

                    </div>
                    <span asp-validation-for="@Model[i].File" class="text-danger"></span>
                    <input hidden asp-for="@Model[i].block.Block_image" type="text" value="@Model[i].block.Block_image" id="Block_image_@i" />
                </div>
                <div class="PreviewPhoto_block">

                    @if (Model[i]?.block?.Block_image != null && Model[i]?.block?.Block_image != "")
                    {
                        <img class="PreviewPhoto" id="PreviewPhoto_@i" src="~/images/@Model[i].block?.Block_image" alt="Logo Image" />

                    }
                    else
                    {
                        <img class="PreviewPhoto" id="PreviewPhoto_@i" src="~/images/Site/no-image-icon-15.png" alt="Logo Image" />
   
                    }
                </div>
            </div>
            <!--end-->
            <!-- Button to remove this specific block -->
            <button type="button" class="remove-button" onclick="removeBlock(this)">❌</button>
        </div>
    }

    <button type="button" id="createBlock">➕ Add</button>
    <input type="submit" value="Next" class="btn btn-primary" />
    @{
        int? v = @Model?.Count() - 1;
         <input type="hidden" value="@v" id="lastStyleIndex" />
    }
   
</form>

@section Scripts{

    <script>
        // Define the createBlock function
        // Define the createBlock function
        // Define the createBlock function
        function createBlock() {
            var form = document.getElementById('Bform');
            var blocs = form.getElementsByClassName('block');

            var lastBlock = blocs[blocs.length - 1];
            var newRow = lastBlock.cloneNode(true); // Clone the last block

            // Update input names with new index
            var lastrowIdx = document.getElementById('lastStyleIndex').value;
            var nextrowIdx = parseInt(lastrowIdx) + 1;

            var elements = newRow.querySelectorAll('input, textarea, select, img, span');
            elements.forEach(function (element) {
                var name = element.getAttribute('name');
                if (name) {
                    element.setAttribute('name', name.replace(/\[\d+\]/g, '[' + nextrowIdx + ']'));
                }
                var id = element.getAttribute('id');
                if (id) {
                    element.setAttribute('id', id.replace(/\d+$/, nextrowIdx));
                }
                var onchange = element.getAttribute('onchange');
                if (onchange && element.tagName === 'INPUT') { // Only update onchange for input elements
                    element.setAttribute('onchange', "document.getElementById('PreviewPhoto_" + nextrowIdx + "').src = window.URL.createObjectURL(this.files[0])");
                }

                var valMsgFor = element.getAttribute('data-valmsg-for');
                if (valMsgFor) {
                    element.setAttribute('data-valmsg-for', valMsgFor.replace(/\[\d+\]/g, '[' + nextrowIdx + ']'));
                }
            });

          
            // Insert the new row before the "Add" button
            var addButton = document.getElementById('createBlock');
            addButton.parentNode.insertBefore(newRow, addButton);

            // Increment the lastStyleIndex value
            document.getElementById('lastStyleIndex').value = nextrowIdx;
        }



        // Function to remove a specific block
        function removeBlock(button) {
            var blockToRemove = button.parentNode;
            blockToRemove.parentNode.removeChild(blockToRemove);

            // Update indexes of remaining blocks
            var form = document.getElementById('Bform');
            var blocs = form.getElementsByClassName('block');
            for (var i = 0; i < blocs.length; i++) {
                var elements = blocs[i].querySelectorAll('input, textarea, select, img, span');
                elements.forEach(function (element) {
                    var name = element.getAttribute('name');
                    if (name) {
                        element.setAttribute('name', name.replace(/\[\d+\]/g, '[' + i + ']'));
                    }
                    var id = element.getAttribute('id');
                    if (id) {
                        element.setAttribute('id', id.replace(/\d+$/, i));
                    }
                    var onchange = element.getAttribute('onchange');
                    if (onchange && element.tagName === 'INPUT') { // Only update onchange for input elements
                        element.setAttribute('onchange', "document.getElementById('PreviewPhoto_" + i + "').src = window.URL.createObjectURL(this.files[0])");
                    }

                    var valMsgFor = element.getAttribute('data-valmsg-for');
                    if (valMsgFor) {
                        element.setAttribute('data-valmsg-for', valMsgFor.replace(/\[\d+\]/g, '[' + i + ']'));
                    }
                });
            }
            // Decrement the lastStyleIndex value
            document.getElementById('lastStyleIndex').value = blocs.length - 1;
        }

        // Attach the event listener to the "Add" button
        document.getElementById('createBlock').addEventListener('click', createBlock);
    </script>


}