Ecomerce/Ecomerce/Controllers/AdminController.cs
using Ecomerce.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Ecomerce.Data;
using Ecomerce.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
//these 2 libarariys are for working with an file 
using System.IO;
using Microsoft.AspNetCore.Hosting;
using static System.Reflection.Metadata.BlobBuilder;
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json;
using Ecomerce.SeessionModels;
using System.IdentityModel.Tokens.Jwt;
using Microsoft.AspNetCore.Authorization;
using System.Linq;

namespace Ecomerce.Controllers
{

   [Authorize(Roles ="Admin,Owner")]
   public class AdminController : Controller
   {

      
       private readonly IWebHostEnvironment _webHost;
       private readonly SystemContext systemContext;

        public AdminController(IWebHostEnvironment webHost,SystemContext _systemContext)
        {

           _webHost = webHost;
            systemContext = _systemContext;
        }
        //first fase in create
       [HttpGet]
       public IActionResult AddProductGenerall()
       {
           
           FirstPartOfFormOfProductViewModel firstPart = new FirstPartOfFormOfProductViewModel() { };

           firstPart.Categories = systemContext.Categorias.Select(x => new SelectListItem() { Value = x.Categoriy_Id.ToString(), Text = x.Categoriy_Name }).ToList();
           firstPart.Sizes = systemContext.Sizes.Select(x => new SelectListItem() { Value = x.SizeID.ToString(), Text = x.size.ToString() }).ToList();

           return View(firstPart);
       }

       [HttpPost]
       public IActionResult AddProductGenerall(FirstPartOfFormOfProductViewModel firstPart)
       {
           if (true)
           {
             string serialized = JsonConvert.SerializeObject(firstPart);
             HttpContext.Session.SetString("generalInfo", serialized);

             return RedirectToAction("SetBlocks");
           }

           return View(firstPart);
       }


        // second faze in create

       [HttpGet]
       public IActionResult SetBlocks()
       {


          List<BlockWithFile> blocks = new List<BlockWithFile>();
          
          blocks.Insert(0, new BlockWithFile { block=new Block()});

          return View(blocks);
       }
       [HttpPost]
       public IActionResult SetBlocks(List<BlockWithFile> blocks)
       {
          


           foreach (var block in blocks)
           {

                if (block.File != null && block.File.Length > 0)
                {
                
                
                    string uniqueFileName = GetUploadedFileName(block.File);
                    if (uniqueFileName != null && uniqueFileName != "")
                    {
                        block.block.Block_image = uniqueFileName;
                    }
                
                }


           }

           if (blocks[0].block.Block_description == null)
           {

              
               return View(blocks);
           }
           else
           {
               string serialized = JsonConvert.SerializeObject(blocks.Select(x => x.block));
               HttpContext.Session.SetString("blocks", serialized);
               return RedirectToAction("SetStyles");
           }


       }

        //third faze in create
       [HttpGet]
       public IActionResult SetStyles()
       {
   
           List<StyleWithFiles> styles = new List<StyleWithFiles>();
           styles.Insert(0, new StyleWithFiles {style=new Style { },files=new List<FileOfImage>() });
           styles[0].style.Style_images = new List<Image>();
           styles[0].style.Style_images.Insert(0, new Image { });
           IFormFile? file = null;
           styles[0].files.Insert(0,new FileOfImage());

       return View(styles);
       }
       [HttpPost]
       public IActionResult SetStyles(List<StyleWithFiles> styles)
       {

       
          
           foreach (var style in styles)
           {

                for(int i= 0; i< style?.files?.Count() ; i++)
                {

                    if (style?.files?[i] != null && style?.files[i].file?.Length >0)
                    {


                        string uniqueFileName = GetUploadedFileName(style.files[i].file);
                        if (uniqueFileName != null && uniqueFileName != "")
                        {
                           style.style.Style_images[i].Image_url = uniqueFileName;
                        }

                    }
                }
               

           }

           if (true)
           {
           // Store the serialized styles in session
               string serialized = JsonConvert.SerializeObject(styles.Select(x=>x.style));
               HttpContext.Session.SetString("styles", serialized);
            
               return RedirectToAction("SetQuntatiy");
           }
           return View(styles);
       }

        // fourth fase in create
       [HttpGet]
       public IActionResult SetQuntatiy()
       {
            FirstPartOfFormOfProductViewModel general= JsonConvert.DeserializeObject<FirstPartOfFormOfProductViewModel>(HttpContext.Session.GetString("generalInfo"));


            List<Size> sizes = new List<Size>();
            foreach (var siz in general?.Product_sizes)
            {
                sizes.Add(systemContext.Sizes.Single(x => x.SizeID == siz));
            }

            List<Style> styles=JsonConvert.DeserializeObject<List<Style>>(HttpContext.Session.GetString("styles"));



            List<StyleSize> quantatis = new List<StyleSize>();
           for (int i = 0; i < styles?.Count(); i++)
           {
               for (int j = 0; j < sizes?.Count(); j++)
               {
                    StyleSize item = new StyleSize();
                    item.Style = styles[i];
                    item.size= sizes[j];
                    item.SizeId = sizes[j].SizeID;
                  
                    item.quantity = 0;
                    quantatis.Add(item);
               }
           }

          
           return View(quantatis);
       }
        [HttpPost]
        public IActionResult SetQuntatiy(List<StyleSize> quantatis)
        {

            string serialized = JsonConvert.SerializeObject(quantatis);
            HttpContext.Session.SetString("quantatis", serialized);
           Console.WriteLine(serialized);
            return RedirectToAction("create");
            
        }

        //the last fase in create => Add to data base
        [HttpGet]
        public IActionResult create()
        {
            Product product = new Product();
            FirstPartOfFormOfProductViewModel generalInfo = JsonConvert.DeserializeObject<FirstPartOfFormOfProductViewModel>(HttpContext.Session.GetString("generalInfo"));

            List<Block>blocks= JsonConvert.DeserializeObject<List<Block>>(HttpContext.Session.GetString("blocks"));

            List<Style>styles= JsonConvert.DeserializeObject<List<Style>>(HttpContext.Session.GetString("styles"));
          
            if (generalInfo == null || blocks == null || styles == null)
            {
                return RedirectToAction("Error");
            }

            product.Product_name = generalInfo?.Product_name;
            product.Product_description = generalInfo?.Product_description;
            product.Product_rate= generalInfo?.Product_rate;

            

            product.Product_Categoriys = generalInfo?.Product_Categoriys.Select(x => new ProductCategoriy() { CategoriyId = x }).ToList();
           
            
            product.Product_sizes= generalInfo?.Product_sizes.Select(x => new ProductSize() { SizeId = x }).ToList();

           
            product.Product_blocks=blocks;
            product.Product_styles=styles;


            string serialized = JsonConvert.SerializeObject(product);
            HttpContext.Session.SetString("product", serialized);

           
            product.Product_sizes = generalInfo?.Product_sizes.Select(x => new ProductSize() { SizeId = x ,size=systemContext.Sizes.Where(s=>s.SizeID==x).FirstOrDefault()}).ToList();

            
            return View(product);
        }

        [HttpPost]
        public IActionResult create(Product product)
        {
            product = JsonConvert.DeserializeObject<Product>(HttpContext.Session.GetString("product"));
           
            systemContext.ProductList.Add(product);
            systemContext.SaveChanges();


            //List<Style> styles = new List<Style>();
            //styles = systemContext.ProductList.OrderBy(p=>p.Product_Id).Last().Product_styles;
            //List<StyleSize> quantatis = JsonConvert.DeserializeObject<List<StyleSize>>(HttpContext.Session.GetString("quantatis"));
            //foreach (var styleSize in quantatis)
            //{
            //    // Find the Style associated with the StyleSize
            //    var style = styles.FirstOrDefault(s => s.Style_name == styleSize.Style.Style_name);
            //    if (style != null)
            //    {
            //        // Assign the found Style to the StyleSize
            //        styleSize.Style = style;
                    

            //    }
            //    styleSize.StyleId = null;
            //    styleSize.SizeId = null;
            //}
            //Console.WriteLine("..............................");

            //string serialized = JsonConvert.SerializeObject(quantatis);
            
            //Console.WriteLine(serialized);
            //systemContext.StyleSizes.AddRange(quantatis);
            //systemContext.SaveChanges();
            return RedirectToAction("Products");
        }


        //Create an file for the image and creat an uniqe name for it
        private string GetUploadedFileName(IFormFile? imgfile)
        {
           string uniqueFileName = null;

           if (imgfile != null)
           {
               string uploadsFolder = Path.Combine(_webHost.WebRootPath, "images");
               uniqueFileName = Guid.NewGuid().ToString() + "_" + imgfile.FileName;

Ecomerce/Ecomerce/Controllers/CartController.cs
using Ecomerce.Data;
using Ecomerce.Models;
using Ecomerce.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace Ecomerce.Controllers
{
    public class CartController : Controller
    {
        private readonly SystemContext systemContext;
        public CartController(SystemContext _systemContext) { 
            this.systemContext = _systemContext;
        }
        List<ShopingCartItemViewModel> items;
        
        public IActionResult CartPage()
        {
            
            if (HttpContext.Session.GetString("CartItems") != null)
            {
                string json = HttpContext.Session.GetString("CartItems");
                items = JsonConvert.DeserializeObject<List<ShopingCartItemViewModel>>(json);
            }
           
            return View(items);
        }
        [HttpPost]
        public IActionResult AddToCart(ShopingCartItemViewModel newitem)
        {
            items = new List<ShopingCartItemViewModel>();
            newitem.Size =systemContext.Sizes.Find(newitem.sizeId).size;
            
            if (HttpContext.Session.GetString("CartItems")!=null)
            {
                string json = HttpContext.Session.GetString("CartItems");
                items = JsonConvert.DeserializeObject<List<ShopingCartItemViewModel>>(json);
            }

            items?.Add(newitem);
            string serializedItems = JsonConvert.SerializeObject(items);

            HttpContext.Session.SetString("CartItems", serializedItems);

            HttpContext.Session.SetString("ItemsCnt", items.Count().ToString());
            return Json(new { Success = true, Counter = items.Count() });
        }

        [HttpGet]
        public IActionResult CheckOut()
        {
            CheckOutViewModel model=new CheckOutViewModel();
                 if (HttpContext.Session.GetString("CartItems") != null)
            {
                string json = HttpContext.Session.GetString("CartItems");
                model.shopings = JsonConvert.DeserializeObject<List<ShopingCartItemViewModel>>(json);
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult CheckOut(CheckOutViewModel model)
        {
            
                // Create a new Customer object
                var customer = new Customer
                {
                    FirstName = model.customer.FirstName,
                    LastName = model.customer.LastName,
                    Country = model.customer.Country,
                    Address = model.customer.Address,
                    City = model.customer.City,
                    Governorate = model.customer.Governorate,
                    PostalCode = model.customer.PostalCode,
                    AdditionalAddressInfo = model.customer.AdditionalAddressInfo,
                    PhoneNumber = model.customer.PhoneNumber,
                    Email = model.customer.Email,
                    IsNewsOn = model.customer.IsNewsOn
                };

                // Add the customer to the database
                systemContext.customers.Add(customer);
                systemContext.SaveChanges();

                customer=systemContext.customers.OrderBy(c=>c.CustomerId).Last();
                //////////////
                var order = new Order
                {
                    OrderNumber = "01",
                    OrderDate = DateTime.Now, // Set the order date to the current date and time
                    CustomerId = customer.CustomerId // Assuming the customer ID is already available in the view model
                };

                // Add the order to the database
                systemContext.orders.Add(order);
                systemContext.SaveChanges();
                order=systemContext.orders.OrderBy(c=>c.OrderId).Last();
                foreach (var item in model.shopings)
                {
                    var orderDetail = new OrderDetails
                    {
                        OrderId = order.OrderId, // Assign the newly created order's ID
                        ProductId = item.productId, // Assuming ProductId is part of ShopingCartItemViewModel
                        StyleId = item.StyleId, // Assuming StyleId is part of ShopingCartItemViewModel
                        SizeId = item.sizeId, // Assuming SizeId is part of ShopingCartItemViewModel
                        Price = item.price, // Assuming Price is part of ShopingCartItemViewModel
                        Quantity = item.quantity, // Assuming Quantity is part of ShopingCartItemViewModel
                        Total = item.price * item.quantity, // Calculate the total price for this item
                        // Set other properties as needed
                    };

                    systemContext.orderDetails.Add(orderDetail);
                }

                // Save changes to the database
                systemContext.SaveChanges();
                // Redirect to another action or view
                return RedirectToAction("ThankYou"); // Example: redirect to a thank you page
            
            return View(model);
        }
        public IActionResult ThankYou()
        {
            HttpContext.Session.SetString("ItemsCnt","0");
            HttpContext.Session.SetString("CartItems", "");
            return View("CartPage");
        }

    }
}

Ecomerce/Ecomerce/Views/Shared/_BlockModelBobUpEdit.cshtml
@model Block



<div class="modal fade" id="BlockModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form asp-controller="Admin" asp-action="UpdateBlock" enctype="multipart/form-data" method="post">

                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Edit Block</h5>
                    <button type="button" class="close" id="closeBlockButton" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <input hidden asp-for="@Model.Product_Id" id="blockProductId"  />
                    <input hidden asp-for="Block_Id" id="PobUbBlock_Id"  />

                    <div>
                        <input asp-for="Block_title" id="PobUbBlock_title" class="form-control" placeholder="TITLE of the block" />
                        <br>
                        <span asp-validation-for="Block_title" class="text-danger"></span>
                    </div>

                    <div style="height:100%">
                        <textarea asp-for="Block_description" id="PobUbBlock_description" class="form-control" placeholder="Description of the block"></textarea>
                        <span asp-validation-for="Block_description" class="text-danger"></span>
                    </div>

                    <div class="block_img">
                        <div class="form-group">
                            <label for="" class="control-label"></label>
                            <div class="custom-file">
                                <input type="file" name="ImageFile" class="custom-file-input" 
                                       onchange="document.getElementById('PreviewPhoto_@Model.Block_Id').src = window.URL.createObjectURL(this.files[0])" />

                            </div>

                            <input hidden asp-for="Block_image" id="PobUbBlock_image" type="text" value="@Model.Block_image" />
                        </div>
                        <div class="">

                            @if (Model.Block_image != null && Model?.Block_image != "")
                            {
                                <img class="PreviewPhoto img-thumbnail" id="PreviewPhoto_@Model.Block_Id" src="~/images/@Model?.Block_image" alt="Logo Image" />

                            }
                            else
                            {
                                <img class="PreviewPhoto img-thumbnail" id="PreviewPhoto_@Model.Block_Id" src="~/images/Site/no-image-icon-15.png" alt="Logo Image" />

                            }
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <input type="checkbox" name="delete" value="true" id="DeleteBlockButton" class="btn btn-danger">
                    <input type="hidden" value="false" name="delete" />
                    <label class="form-check-label" for="delete">Delete Block</label>
                    <button type="button" id="MaincloseBlockButton" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" id="SaveBlockButton" class="btn btn-primary">Save changes</button>
                </div>

            </form>
        </div>
    </div>
</div>

Ecomerce/Ecomerce/Views/Shared/_Cart.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<li class="icon">
    @{

        if (HttpContextAccessor.HttpContext.Session.GetString("ItemsCnt") != null)
        {
            <a asp-controller="Cart" asp-action="CartPage" id="Cart">
                <i class="fa-solid fa-cart-shopping"></i>
                <span id="CartText">@HttpContextAccessor.HttpContext.Session.GetString("ItemsCnt")</span>
            </a>
        }
        else
        {
            <a asp-controller="Cart" asp-action="CartPage" id="Cart">
                <i class="fa-solid fa-cart-shopping"></i>
                <span id="CartText">0</span>
            </a>
        }
    }

    
  

</li>

Ecomerce/Ecomerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ecomerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ecomerce.styles.css" asp-append-version="true" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ecomerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Ecomerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Ecomerce/Ecomerce/Views/Shared/_SideNavBar.cshtml
<link href="~/css/_css/_sidenavbar.css" rel="stylesheet" />
<nav class="navbar">
    <ul class="navbar__menu">
        <li class="navbar__item">
            <a asp-action="OpenAccount" asp-controller="Account" class="navbar__link"><i class="fas fa-home"></i><span>DasHBoard</span></a>
        </li>
        <li class="navbar__item">
            <a href="#" class="navbar__link"><i class="far fa-envelope"></i><span>Messages</span></a>
        </li>
        <li class="navbar__item">
            <a asp-controller="Admin" asp-action="Customers" class="navbar__link"><i class="fas fa-users"></i><span>Customers</span></a>
        </li>
        <li class="navbar__item">
            <a asp-controller="Admin" asp-action="Orders" class="navbar__link"><i class="fas fa-shopping-cart"></i><span>orders</span></a>
        </li>
        <li class="navbar__item">
            <a asp-controller="Admin" asp-action="Products" class="navbar__link"><i class="far fa-folder"></i><span>Products</span></a>
        </li>
        <li class="navbar__item">
            <a asp-controller="Admin" asp-action="HR" class="navbar__link"><i class="fas fa-archive"></i><span>HR</span></a>
        </li>
        <li class="navbar__item">
            <a asp-controller="Home" asp-action="Help" class="navbar__link"><i class="far fa-question-circle"></i><span>Help</span></a>
        </li>
        <li class="navbar__item">
            <a asp-action="Logout" asp-controller="Account" class="navbar__link"><i class="fas fa-sign-out-alt"></i><span>LogOut</span></a>
        </li>
    </ul>
</nav>

Ecomerce/Ecomerce/Views/Shared/_StyleModelPobUpEdit.cshtml
@using Ecomerce.SeessionModels;
@model List<StyleWithFiles>



<div class="modal fade" id="StyleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="Sform" enctype="multipart/form-data" asp-controller="Admin" asp-action="UpdateStyle" method="post">

                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Edit Style</h5>
                    <button type="button" class="close" id="closeStyleButton" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <input hidden asp-for="@Model[0].style.Product_Id" id="StyleProductId" />
                    <input hidden asp-for="@Model[0].style.Style_Id" id="PobUbStyle_Id" />

                    <div>
                        <input asp-for="@Model[0].style.Style_name" id="PobUbStyle_title" class="form-control" placeholder="Style name" />
                        <br>
                        <span asp-validation-for="@Model[0].style.Style_name" class="text-danger"></span>
                    </div>

                    <div style="height:100%">
                        <input asp-for="@Model[0].style.Style_price" id="PobUbStyle_Price" class="form-control" placeholder="Style Price" />
                        <span asp-validation-for="@Model[0].style.Style_price" class="text-danger"></span>
                    </div>
                    <div class="" style="display:grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));grid-gap:5px;">
                        @for(int i = 0,x=0; i < Model[0].files.Count(); i++)
                        {
                            
                            
                            <div class="block_img" style="width:50%">
                                <div class="form-group">
                                    <label for="" class="control-label"></label>
                                    <div class="custom-file">

                                        <input asp-for="@Model[x].files[i].file" type="file" class="custom-file-input" id="customFile_@i" value=""
                                               onchange="document.getElementById('PreviewPhoto_@i').src = window.URL.createObjectURL(this.files[0])" type="file"/>

                                    </div>

                                    <input hidden asp-for="@Model[x].style.Style_images[i].Image_url" id="PobUbStyle_image_@i" type="text"  />
                                </div>
                                <div class="">

                                        <img class="PreviewPhoto img-thumbnail" id="PreviewPhoto_@i" src="~/images/Site/no-image-icon-15.png" alt="Logo Image" />

                                    
                                </div>
                            </div>

                        }
                    </div>

                </div>
                <div class="modal-footer">
                    <input type="checkbox" name="delete" value="true" id="DeleteStyleButton" class="btn btn-danger">
                    <input type="hidden" value="false" name="delete" />
                    <label class="form-check-label" for="delete">Delete Style</label>
                    <button type="button" id="MaincloseStyleButton" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" id="SaveStyleButton" class="btn btn-primary">Save changes</button>
                </div>

            </form>
        </div>
    </div>
</div>